#!/bin/bash
###########################################################################
# if this file is edited, then a new hydroshare container must be pushed. #
#  developers should modify init_steps                                    #
###########################################################################
./init_github

./init_steps

