#!/bin/bash

# ##########################################################
# this file should be called after the init_github, and init_modules scripts. #
# ##########################################################

if [ -n "$POSTGIS_PORT_5432_TCP_ADDR" ]; then
POSTGIS_HOST=$POSTGIS_PORT_5432_TCP_ADDR
export POSTGIS_HOST
REDIS_HOST=$REDIS_PORT_6379_TCP_ADDR
export REDIS_HOST
REDIS_PORT=6379
POSTGIS_PORT=5432
export REDIS_PORT
export POSTGIS_PORT
fi
# docker init file. This will bring up all the services: celery, uwsgi, sshd, and nginx
service nginx restart
/usr/sbin/sshd

cd /home/docker/hydroshare
python manage.py syncdb
python manage.py migrate
python manage.py collectstatic --noinput
export PYTHONPATH=/home/docker/hydroshare
su docker -c "PYTHONPATH=/home/docker/hydroshare celery worker -A celeryworker -E -D"
uwsgi --ini /home/docker/hydroshare/uwsgi.ini